version: '3.8'

services:
  vatsim-analyzer:
    image: ghcr.io/justusplays78/vatsim-feed-listener:allinone
    container_name: vatsim-analyzer
    restart: always
    ports:
      - '9080:80' # Frontend (Nginx)
      - '3001:3001' # Backend API
    volumes:
      # Persist event cache
      - vatsim-event-cache:/app/backend/event-cache.json
    environment:
      - PORT=3001
      - NODE_ENV=production
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost/',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  vatsim-event-cache:
    driver: local
