version: '3.8'

services:
  vatsim-flight-analyzer:
    build: .
    container_name: vatsim-flight-analyzer
    ports:
      - "9080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Optional: Für lokale Entwicklung
      - ./public:/app/public:ro
      - ./server.js:/app/server.js:ro
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vatsim-analyzer.rule=Host(`moehre.intjulscha.de`)"
      - "traefik.http.routers.vatsim-analyzer.entrypoints=websecure"
      - "traefik.http.routers.vatsim-analyzer.tls.certresolver=letsencrypt"
      - "traefik.http.services.vatsim-analyzer.loadbalancer.server.port=3000"

networks:
  web:
    external: true